### ISSUE TITLE
Default Grafana login credentials

### ISSUE THREAD

**Issue by ShurikAg** [digitalocean/Kubernetes-Starter-Kit-Developers#112]
I am following this kit step by step and got to Grafana section. 
There is no information about default Grafana login credentials, so I took the one from the [official docs](https://grafana.com/docs/grafana/latest/getting-started/getting-started/#step-2-log-in). However, `admin` for username and password do not work.

How can I resolve that?

**Comment by v-ctiutiu** [comment]
Hi @ShurikAg 

Starter Kit is using by default the default credentials from the [prom-stack-values](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-prometheus-stack/assets/manifests/prom-stack-values-v30.0.1.yaml#L38) Helm file provided in this repo. You can also find the same information in the corresponding [section](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-prometheus-stack/README.md#step-4---visualizing-metrics-using-grafana) from the Starter Kit Prometheus tutorial. Just search there for `default credentials`.

It's not the standard credentials, because that's how the Helm chart maintainers set them initially, I guess. So, for historical reasons credentials remained the same in the Starter Kit as well.

As a kind remainder, for any questions related to the Starter Kit tutorial in general, please use the [Discussions](https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/discussions) section from this repo. Thanks.

Hope it helps.

**Comment by ShurikAg** [comment]
Thank you! Found it
